sudo: false
language: python

python: "3.5"

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install -r requirements.txt
  - pip install coverage coveralls

script:
  - coverage run --source='.' manage.py test

after_success:
  - coveralls