sudo: false
language: python

python: "3.5"

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install -r Trabalho_1/requirements.txt
  - pip install coverage coveralls

script:
  - coverage run --source='.' Trabalho_1/manage.py test

after_success:
  - coveralls
